id: P4843B98B
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: pt
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    b8a73777f511436b9bdbc1dc60fa6154:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    a437959b596740ef824e281b4e71f8d9:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    b2045eb48ee84446a8c9f971a2d49b46:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    b654049fca9e48769dc42d6f60e73048:
      title: Verses on the Buddha's Previous Lives
      parent: History
    d711cb71fdc8482fb2071863aed505ec:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    ebcee62a0b0e4bd6bc4700bfe6ea8d98:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    938dfbc934624fcf994d1bef3176e0e7:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    31b2ae730ea14154878f6c0813412f46:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    aec51df45e124fc581856221bf9e4f27:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    12b5e9792c0c4e05ab1ddac233b699df:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    a3a050af4bb14603baabcc28fffebab5:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    e71c2b02880d406fa8b30a370ebeaebc:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    1f839a94d7114e7bbdb154eceb083753:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.227723'
last_modified_at: '2022-03-01T03:05:43.227725'
